### ISSUE TITLE
Screen

### ISSUE THREAD

**Issue by McKitten** [GeheimagentNr1/AutoRestart#1]
RE 1.7.x (tho possibly backported)

I have multiple servers on the one remote machine and so screen has the omega of applications, however I've found AutoRestart can close the server whilst in a screen session but not reopen it in that session.

The most awesomest solution would be for the mod to know the ID and reopen the server in it, continuing the capability to monitor it remotely.

Not sure how to script this one as the screen PID? will be modified each month when the entire server updates and reboots; and I can't really script to save myself anyways, I fail at 1 language let alone 4+.

**Comment by GeheimagentNr1** [comment]
You could use the scripts I provided here: [https://github.com/GeheimagentNr1/AutoRestart/wiki/Linux-Scripts#external-restart-script](https://github.com/GeheimagentNr1/AutoRestart/wiki/Linux-Scripts#external-restart-script)

If you are using them, then the server restarts inside the screen and the screen is never closed.
