### ISSUE TITLE
Server won't restart

### ISSUE THREAD

**Issue by ToastiMan** [GeheimagentNr1/AutoRestart#2]
**Versions**
Minecraft Version: 1.18.2
Minecraft Forge Version: 40.0.42
Mod Version: 2.0.0

**Log files**
Please append the log, debug-log and if available the crash-log files.

**Describe the bug**
I tried every step in your Instructions, also tried the external restart files, but somehow the server doesn't want to restart. 
In the restart file that's in the auto_restart folder is only a "1".

In the latest.log you can see the line:
[08Apr2022 19:39:00.438] [Server thread/INFO] [de.geheimagentnr1.auto_restart.util.ServerRestarter/]: Saving restart status "EXCEPTION" to file

I had the rename the attached files to post them here.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
Server restarting

**Screenshots**

**Additional context**
[latest.log](https://github.com/GeheimagentNr1/AutoRestart/files/8454225/latest.log)
[auto_restart-server.txt](https://github.com/GeheimagentNr1/AutoRestart/files/8454226/auto_restart-server.txt)
[runbat.txt](https://github.com/GeheimagentNr1/AutoRestart/files/8454235/runbat.txt)
[runsh.txt](https://github.com/GeheimagentNr1/AutoRestart/files/8454236/runsh.txt)

**Comment by GeheimagentNr1** [comment]
In the latest.log it looks like the server never is running without any issues, and a command like "/restart" or "/stop" is never called, Because there are no log information about the world being saved, and the server is getting stopped.  
From the auto\_restart-server.txt file, it looks like, that you are starting the server with a "start.sh", that you didn't provide in this issue. Do you a file named "start.sh" in your server directory? And if yes, do you have the permissions to execute it?

**Comment by ToastiMan** [comment]
Sorry, i uploaded the wrong latest.log. The right one is attached here. 
I renamed the "run.sh" which is attached above to "start.sh". Permission for start.sh is set to 755
[latest.log](https://github.com/GeheimagentNr1/AutoRestart/files/8456790/latest.log)
[startsh.txt](https://github.com/GeheimagentNr1/AutoRestart/files/8456791/startsh.txt)
[user_jvm_args.txt](https://github.com/GeheimagentNr1/AutoRestart/files/8456792/user_jvm_args.txt)
.

**Comment by ToastiMan** [comment]
Funny enough, i just noticed that with this mod installed there's a conflict with biomesop and byg. Both can't generate their biomes anymore. As soon as i deactivate the autorestart mod, everythings fine again

**Comment by GeheimagentNr1** [comment]
Please try to add "-d -m" to the screen command in your start.sh file, like in my examples: https://github.com/GeheimagentNr1/AutoRestart/wiki/Simple-Instructions%3A-1.3-Setup-%28MC-1.17.1-or-newer%2C-Linux%2C-Start-Script%29
