### ISSUE TITLE
Reshow Hidden Command Prompt on Restart?

### ISSUE THREAD

**Issue by joelra** [GeheimagentNr1/AutoRestart#3]
Minecraft Version: 1.16.5
Server OS: Windows

Issue: How do I reshow the hidden command prompt after an auto restart?

Description: I have an external script I'm using that just calls a batch file to loop starting the minecraft server after checking the restart code. When I first start the server, a command prompt opens and everything is visible. After a restart takes place though via the mod, the command prompt window is hidden. Is there a way to re-show that command prompt? Or not have it hidden?

**Comment by GeheimagentNr1** [comment]
What kind of restart script and what configuration of the Auto Restart are you using?  
Normally, the restart mod should not have an influence on the command prompt. I didn't know of any case where the command prompt got invisible before.
