### ISSUE TITLE
1.19.2 - Failed to Execute

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [GeheimagentNr1/AutoRestart#7]
Forge Version 43.2.28
Auto Restart Version AutoRestart-1.19.2-2.0.1
Dedicated Windows 11 Server With Admin Rights

https://gist.github.com/P3rf3ctXZer0/8982f4df6e8d53e0459302ea4bc4d5ba

**Comment by GeheimagentNr1** [comment]
Did you already check the Setup Guide?
https://github.com/GeheimagentNr1/AutoRestart/wiki/Simple-Instructions
There is described how to set up the mod, for different operating system and different Minecraft versions.
